[package]
name = "g1r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.45"
async-openai = "0.9.3"
tokio = { version = "1.23.0", features = ["full"] }
rand = "0.8.4"
regex = "1.7.1"
toml = "0.7.2"
serde = "1.0.152"
tokio-openssl = "0.6.3"
colored = "2"
tokio-socks = "0.5.1"
socks = "0.3.4"
random_word = "0.3.0"
leetspeak = "0.2.0"
irc = "0.15.0"
futures = "0.3.27"
futures-util = "0.3.27"