server = "irc.supernets.org"
port = 6697
use_ssl = true
nickname = "g1r"
channel = "#superbowl"
sasl_username = ""
sasl_password = ""
capabilities = ["sasl"]
use_proxy = false
proxy_type = "socks5"
proxy_addr = "127.0.0.1"
proxy_port = 9050
proxy_username = "" 
proxy_password = ""
