nick = "g1r"
server = "ircd.chat"
port = 6697
password = ""
channels = [ "#sad", "#s4d", "wiki", "#emo", "#tcpdirect", "#macros", "#b0tsh0p" ] #add key access 
admin_users = ["s4d", "sad", "g", "d", "h3x", "kayos", "moony"] # add host identification
ignore_users = ["maple", "aibird", "professorOak", "van"]
openai = "sk-"
model = "gpt-3.5-turbo"
accents = "funny, completely insane, and hyperactive"  
personalities = "GIR from Invader Zim"

# SMTP

# TOR
proxy_server = "127.0.0.1"
proxy_port = 9050

# INVADER SETTINGS
proxy_list = "./proxies.txt"
